name: pcl_env
channels:
  - ccordoba12
dependencies:
  - python=3.6
  - matplotlib
  - pcl
  - python-pcl
  - nb_conda
  - nb_conda_kernels
  - keras
  - tensorflow
  - pillow
  - glob2
  - progressbar2